Update evo.yml

diff --git a/.github/workflows/evo.yml b/.github/workflows/evo.yml
--- a/.github/workflows/evo.yml
+++ b/.github/workflows/evo.yml
@@ -11,14 +11,17 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Download EvolutionX ZIP using wget
+      - name: Ensure wget is installed and Download EvolutionX ZIP
         run: |
-          sudo apt update
-          sudo apt install wget -y
+          if ! command -v wget &> /dev/null; then
+            echo "wget not found, installing..."
+            sudo apt update
+            sudo apt install -y wget
+          fi
           wget -O EvolutionX-15.0-20250302-d2x-10.3-Official.zip https://sourceforge.net/projects/evolution-x/files/d2x/15/EvolutionX-15.0-20250302-d2x-10.3-Official.zip/download
 
       - name: Upload EvolutionX ZIP as Artifact
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v2
         with:
           name: EvolutionX-15.0-20250302-d2x-10.3-Official
           path: EvolutionX-15.0-20250302-d2x-10.3-Official.zip
