Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,6 +53,7 @@ on:
         options:
           - true
           - false
+
 jobs:
   process_video:
     runs-on: ubuntu-latest
@@ -78,13 +79,17 @@ jobs:
         uses: actions/checkout@v4
       
       - name: Download encrypted file
-        run: curl -L "${{ secrets.URL }}" -o cookies.txt.gpg || true  # Continue even if this fails
+        run: |
+          # Capture the current directory
+          CURRENT_DIR=$(pwd)
+          curl -L "${{ secrets.URL }}" -o cookies.txt.gpg || true  # Continue even if this fails
 
       - name: Decrypt file (if exists)
         run: |
-          if [ -f cookies.txt.gpg ]; then
+          # Use the previously captured directory
+          if [ -f "cookies.txt.gpg" ]; then
             echo "${{ secrets.AES_PASSWORD }}" | gpg --batch --passphrase-fd 0 --decrypt cookies.txt.gpg > cookies.txt
-            if [ -f cookies.txt ]; then
+            if [ -f "cookies.txt" ]; then
               echo "Decryption successful, using cookies.txt"
             else
               echo "Decryption failed, using default method"
@@ -126,11 +131,10 @@ jobs:
       - name: Download Video
         run: |
           cd videos
-          # Check if cookies.txt exists and adjust the path accordingly
-          if [ -f "../cookies.txt" ]; then
-            COOKIE_OPTION="--cookies ../cookies.txt"
-          elif [ -f "cookies.txt" ]; then
-            COOKIE_OPTION="--cookies cookies.txt"
+          COOKIE_FILE="${CURRENT_DIR}/cookies.txt"
+          # Check if the decrypted cookies.txt exists, and use the full path
+          if [ -f "$COOKIE_FILE" ]; then
+            COOKIE_OPTION="--cookies $COOKIE_FILE"
           else
             COOKIE_OPTION=""
           fi
